### ISSUE TITLE
ERROR: Migration admin.0001_initial is applied before its dependency accounts.0001_initial

### ISSUE THREAD

**Issue by leobang17** [LikeLion-CAU-9th/Nativing2#4]
정호님 푸시한거 풀받아서 실행하려 했는데 계속 이 오류가 뜨더라구요.

`db.sqlite3` 이랑 
`accounts/migrations` 파일에서 `__init__.py` 를 제외한 파일들을 삭제하고 
```
$ python manage.py makemigrations
$ python manage.py migrate
```
하면 에러 없이 정상적으로 마이그레이션 됩니다 !

---

그리고 왜인지 모르겠는데 migrations 파일이 푸시가 되더라구요..? 
그래서 이 에러가 생긴거 같아요.

저번에 아이디어톤 할 때는 푸시가 안되게 했던 거로 기억하는데, 막상 gitignore 파일 확인하면 똑같구,,
왜인지 아시는분??

**Comment by oereo** [comment]
저희 settings.py 보면 기존 user model 이 장고에서 기본으로 제공해주는 admin을 통해서 superuser를 만들었다면 user model을 커스텀함으로써 충돌이 생겼을거에요!! 그래서 위의 방식으로 migration 파일들을 다 삭제해주고 하는것으로 해결해도 되고! 아니면 fake migrate 방법으로 해결을 하셔도 좋습니다!!

앗 그리고 migration 파일을 .gitignore로 넣으시면 안되요!! migration 파일이 결국 DB에 적용시킬 사항들이 적혀있는 파일이기 때문에 서로 공유가 되어야됩니다!!

**Comment by leobang17** [comment]
핳 감사합니다 ㅋㅋㅋㅋ 이해가 되었어요

**Comment by jjanggyu** [comment]
이슈 닫아도 될 거 같아요! 제출 전에 닫읍시다!
